### PR TITLE
Mock AWS resources in tests 

### LINKED ISSUE #2: Test cases not passing
**Describe the issue**
All the test cases fail when ``` for i in `ls tests/test_*`; do python3 $i; done ``` is run . Most of the errors point to the reflect function in 
https://github.com/architect/functions-python/blob/master/arc/__init__.py 
I'll like to know more about the ARC_CLOUDFORMATION environment variable used in this code

### PR DESCRIPTION
**Pull request by lpetre**
Sorry, this PR got larger than I wanted it to. It includes:
- [x] Python CI github actions
- [x] Small fix for import error in arc.queues
- [x] Converting project to use [pipenv](https://pipenv.pypa.io/en/latest/)
- [x] Converting project to use [pyproject.toml, setup.cfg, and pep517.build](https://setuptools.readthedocs.io/en/latest/userguide/quickstart.html) (replaces setup.py)
- [x] Converting project to use [pytest](https://docs.pytest.org/en/latest/)
- [x] Converting project to use [moto mocks](http://docs.getmoto.org/en/latest/docs/getting_started.html)
- [x] Test coverage enforcement (currently enforcing %51 coverage)
- [x] README updates

The tests all pass (fixes #2) w/ the following:
```
$ pipenv install
$ pipenv run pytest
```

Some planned work (for future PRs):
- Sphinx documentation
- Flake8, black, isort, mypy enforcement
- Automate pypi release w/ github actions
- JWE session support ([in progress](https://github.com/lpetre/functions-python/compare/mock_boto3...lpetre:add_jwe_sessions))

Please let me know what you think. I'm happy to break these into smaller PRs if that is easier to review.

### CODE REVIEW

**Comment by ryanblock** [comment]
@lpetre first, **thank you** for taking this on. This is really exciting.

May or may not be helpful, but per the now-closed https://github.com/architect/functions-python/pull/5/, just want to make sure we've got full background on `boto3`. (And apologies in advance if I'm telling you anything you already know.)

So Lambda bundles their SDKs in their various Lambda images; generally these SDKs are quite large (example: the JS SDK is ~50MB). In order to keep Lambda cold starts low, we want to keep Lambda sizes as small as possible. Adding the SDK as an explicit requirement of our runtime helpers means excess code payload weight that has a meaningful impact on coldstart times.

So, as in the case of the JS version of Architect Functions, we ensure `aws-sdk` is included in developer dependencies for testing, but rely on the built-in version during runtime. Hopefully that all makes sense!

**Comment by lpetre** [comment]
@ryanblock thanks for the background! It is simple to move boto3 to be a developer dependency, the Pipfile change lets us make that distinction.

**Comment by lpetre** [comment]
@ryanblock one idea, could architect have an exclude list when building the python/nodejs/etc lambda bundles?

**Comment by lpetre** [comment]
Reading about SAM and Cloudformation, it does not seem easy to exclude files

**Comment by lpetre** [comment]
Does `functions-ruby` take a similar approach? I'm not too familiar with `Gem::Specification`. I can't tell if these create an install dependency: https://github.com/architect/functions-ruby/blob/master/architect-functions.gemspec#L21-L26

**Comment by ryanblock** [comment]
> It is simple to move boto3 to be a developer dependency, the Pipfile change lets us make that distinction.

That's great!

> ... could architect have an exclude list when building the python/nodejs/etc lambda bundles?

We could, but that's a tough call. We have seen instances where people really need to bundle the SDK anyway. An example we've seen: AWS updates the pre-bundled SDKs irregularly, but occasionally they'll ship a new feature that someone really needs right then, so they'll force-bundle it a second time to get that feature until such time as Lambda updates the SDK version.

> Does functions-ruby take a similar approach?

Good question, it _should_, and if it doesn't I'd consider that a bug, because the principles in play here remain the same! But I am not a Ruby hacker, so I'll defer to @brianleroux, et al!

**Comment by lpetre** [comment]
@ryanblock @brianleroux any other concerns with this? I'm eager to see it merged so I can open other PRs. I did move the boto3 dependency to be dev-only, not sure if you saw that.

**Comment by ryanblock** [comment]
Sorry, wasn't clear that you were all sorted here! I'm good if you are. @brianleroux?

**Comment by brianleroux** [comment]
looks good! thx @lpetre !!!

**Pull request merged**
