### PR TITLE
Make sure we truncate ARC_APP_SECRET to 16 bits for the jwe key

### PR DESCRIPTION
**Pull request by lpetre**
- This matches the behavior in node-webtoken
 - Add tests to validate different user supplied keys

### CODE REVIEW

**Comment by lpetre** [comment]
Bah, something is wrong with the pip caching in the CI workflow

**Comment by lpetre** [comment]
@ryanblock do you know what happens in the node version if the ARC_APP_SECRET is too short?

**Comment by ryanblock** [comment]
@lpetre I do now! (Over 2 years later... 🙃) [`node-webtokens`](https://www.npmjs.com/package/node-webtokens) just blows up.

**Comment by ryanblock** [comment]
See also: https://github.com/architect/functions/issues/548

**Comment by ryanblock** [comment]
Ok, lots of updates on this. Per https://github.com/architect/functions/pull/549, we will be updating the JWE key stuff in Node.js to ensure proper interop here (and in Ruby).

**Pull request merged**
